name: 'Check Config Builders'
description: 'Action for check if project is configured'
author: 'Lucas Diniz'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'file-text'
  color: 'green'

inputs:
  env_path:
    description: 'Path env file for check config'
    required: true
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
# Define your outputs here.
outputs:
  is_configured:
    description: 'If project is configured'

runs:
  using: node20
  main: dist/index.js
